sudo: false

language: python

python:
  - 2.7

install:
  - pip install codecov
  - pip freeze > requirements.txt

script:
  - coverage erase
  - coverage run -m py.test test_test.py
  - coverage xml
  

after_success:
  - codecov
