sudo: false

language: python

python:
  - 2.7

install:
  - pip install codecov
  - pip freeze > requirements.txt

script:
  - coverage erase
  - coverage xml
  - codecov --token=9491677c-40f1-4982-9a32-f0fd7d12b477

after_success:
  - codecov
